<a href="https://colab.research.google.com/github/cnddlf/2022_1_Study_AI/blob/main/CNN(0316).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 배달 시간 = 거리 * w+b
import tensorflow as tf

# 배달 시간
label = 33
distance=850

# tensorflow 형식의 변수 지정
# 실수 0으로 지정
w=tf.Variable(0.)
b=tf.Variable(0.)

In [ ]:
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [ ]:
b.numpy()

0.0

In [ ]:
pred = distance * w + b
pred

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
pred-label

<tf.Tensor: shape=(), dtype=float32, numpy=-33.0>

In [ ]:
tf.square(pred-label)

<tf.Tensor: shape=(), dtype=float32, numpy=1089.0>

In [ ]:
# 손실 함수는 예측값과 실제값의 차이를 줄이기 위한 함수이다.
def loss_func():
  # 예측값 계산
  pred = distance * w + b
  # 실 결과인 label과 예측값 사이의 손실 정도를 계산하여 0과 가까워 질때 까지 반복
  return tf.square(pred-label)

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(1000):
  opt.minimize(loss_func, var_list=[w,b])
  print(w.numpy(), ' : ', b.numpy())

0.10000298  :  0.10000298
0.072968654  :  0.072968654
0.026800007  :  0.026800007
-0.0020025019  :  -0.0020025056
0.00081239105  :  0.0008123822
0.023237752  :  0.023237737
0.05050058  :  0.050500557
0.06855723  :  0.0685572
0.06996406  :  0.06996402
0.057282414  :  0.057282377
0.037990965  :  0.037990928
0.020989394  :  0.020989357
0.013538582  :  0.013538543
0.017642342  :  0.0176423
0.03012839  :  0.030128349
0.045043036  :  0.04504299
0.055908434  :  0.05590839
0.058445275  :  0.05844523
0.05245648  :  0.052456435
0.04127647  :  0.041276425
0.030041266  :  0.030041222
0.023598433  :  0.023598388
0.024329802  :  0.024329757
0.031257026  :  0.031256977
0.040849898  :  0.040849846
0.04866912  :  0.048669063
0.05134464  :  0.051344585
0.04810774  :  0.048107684
0.04092364  :  0.040923584
0.033391293  :  0.033391237
0.029043203  :  0.029043145
0.029667817  :  0.029667757
0.034555677  :  0.034555618
0.041030608  :  0.041030545
0.045833427  :  0.04583336
0.04674077  :  0.0467407
0.0436234

In [ ]:
distance * w+b

<tf.Tensor: shape=(), dtype=float32, numpy=32.999996>

In [ ]:
# 위의 코드를 이용하여 최적의 w, b를 구하고 그 때까지의 횟수를 구하시오.

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

w_back = tf.Variable(0.)
b_back = tf.Variable(0.)

cnt = tf.Variable(0.)

while True:
  opt.minimize(loss_func, var_list=[w,b])
  pred = distance*w+b

  if(w_back.numpy()==w.numpy()) and (b_back.numpy()==b.numpy()) or cnt.numpy()>1000:
    break
  w=tf.Variable(0.)
  b=tf.Variable(0.)

  cnt.assign_add(1)

print(cnt.numpy(), ' : ', w.numpy(), ' : ', b.numpy())

1001.0  :  0.2516035  :  0.2516035


In [ ]:
import tensorflow as tf

device_name=tf.test.gpu_device_name()

if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')