<a href="https://colab.research.google.com/github/cnddlf/2022_1_Study_AI/blob/main/%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0(220218).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
# sklearn의 동작 유무 확인, 버전 확인
sklearn.__version__

'1.0.2'

In [ ]:
from sklearn.datasets import load_iris

# iris 정보를 얻어오기
iris = load_iris()
iris
# 타입 확인
type(iris)
# 가지고 있는 key 정보(내부 정보)
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# print(iris['DESCR'])
iris['data_module']

'sklearn.datasets.data'

In [ ]:
# iris_data = iris.data
iris_data = iris['data']
iris_data

type(iris_data)
# :의 왼쪽은 시작, 오른쪽은 끝, 없으면 0이 생략
print(iris_data[:5])
iris_data[1]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


array([4.9, 3. , 1.4, 0.2])

In [ ]:
iris_target = iris.target
iris_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris_feature_names = iris.feature_names
iris_feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
import pandas as pd

iris = load_iris()
# data와 feature 정보로 dataframe 생성
df_iris = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
# 상위 5개의 데이터 확인
df_iris.head()

# 각 데이터별 결과 저장
df_iris['label'] = iris['target']
# 하위 5개의 데이터 확인
df_iris.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
145      2  
146      2  
147      2  
148      2  
149      2

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target)
X_train[:5]

print('전체 데이터 크기 : ', iris['data'].size)
print('train 데이터의 기본 크기는 전체의 75% : ', X_train.size)

전체 데이터 크기 :  600
train 데이터의 기본 크기는 전체의 75% :  448


> 위의 코드를 실행할 때마다 다른 결과를 얻게 된다.

```
array([[5.6, 2.5, 3.9, 1.1],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [7.2, 3.2, 6. , 1.8],
       [6.1, 2.6, 5.6, 1.4]])

array([[5.1, 3.4, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 2.8, 4.8, 1.4]])
```


In [ ]:
# 위와 같이 실행할때마다 다른 결과가 나타나는 것을 방지하기 위해 random_state 사용
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=62)
X_train[:5]

array([[5.5, 2.3, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6.9, 3.2, 5.7, 2.3],
       [5.8, 4. , 1.2, 0.2]])

In [ ]:
# 처음부터 3번째 열까지, 모든 feature 정보까지 출력
df_iris.iloc[:3, :4]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [ ]:
train_test_split(df_iris.iloc[:, :4], df_iris['label'])

[     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 84                 5.4               3.0                4.5               1.5
 26                 5.0               3.4                1.6               0.4
 52                 6.9               3.1                4.9               1.5
 28                 5.2               3.4                1.4               0.2
 69                 5.6               2.5                3.9               1.1
 ..                 ...               ...                ...               ...
 40                 5.0               3.5                1.3               0.3
 16                 5.4               3.9                1.3               0.4
 116                6.5               3.0                5.5               1.8
 60                 5.0               2.0                3.5               1.0
 123                6.3               2.7                4.9               1.8
 
 [112 rows x 4 columns],
      sepal length (cm)  

In [ ]:
df_iris_data = df_iris.drop('label', axis=1)
df_iris_data

df_iris_label = df_iris['label']
df_iris_label

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: label, Length: 150, dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# 모델 얻어오기
df_clf = DecisionTreeClassifier()
# 모델 생성
df_clf.fit(X_train, y_train)

DecisionTreeClassifier()

DecisionTreeClassifier()

In [ ]:
# 검증데이터를 통해 예측 정보 얻기
pred = df_clf.predict(X_test)
# 예측 정보 출력
print(pred)
# 실 데이터 출력
print(y_test)

[2 2 0 0 2 2 2 0 1 1 2 1 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]
[2 2 0 0 2 1 2 0 1 1 2 2 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]


In [ ]:
from sklearn.metrics import accuracy_score

print('예측 정확도 : {0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도 :  0.9333


In [ ]:
# iris 정보를 읽어 들이고 데이터와 타겟 정보를 각각 5개씩 출력하시오

from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris['data']
iris_label = iris['target']

print(iris_data[:5])
print(iris_label[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier

In [ ]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5)

In [ ]:
# shape이라는 것은 데이터의 모양을 보여준다.
iris_data.shape
# 행의 개수
iris_data.shape[0]
# 열(feature)의 개수
iris_data.shape[1]

4

In [ ]:
for train_idx, test_idx in kfold.split(iris_data):
  print('train index')
  print(train_idx)
  print('test index')
  print(test_idx)
  print('='*50)

train index
[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
test index
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
train index
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 12

In [ ]:
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier()
kfold=StratifiedKFold(n_splits=3)


cv_accuracy=[]
n=iter = 1

for train_idx, test_idx in kfold.split(iris_data, iris_label):
  # 훈련용 데이터
  X_train = iris_data[train_idx]
  y_train = iris_label[train_idx]

  # 검증 데이터
  X_test = iris_data[test_idx]
  y_test = iris_label[test_idx]

  # 모델 학습
  dt_clf.fit(X_train, y_train)
  # 예측 출력
  pred = dt_clf.predict(X_test)
  # 정확도 출력
  acc = round(accuracy_score(y_test, pred), 4)
  print(acc)

print('='*50)
print(round(np.mean(cv_accuracy), 4))

0.98
0.94
0.96
nan


/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [ ]:
x_test=[[3, 3, 1, 1]]
dt_clf.predict(x_test)

if pred[0]==1:
  print('<p>setosa</p>')

In [ ]:
df_iris['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=3)

kfold = KFold(n_splits=3)

for train_idx, test_idx in kfold.split(iris_data):
  y_train = df_iris['label'].iloc[train_idx]
  y_test = df_iris['label'].iloc[test_idx]

  print(y_train.value_counts())
  print(y_test.value_counts())
  print('='*50)



1    50
2    50
Name: label, dtype: int64
0    50
Name: label, dtype: int64
0    50
2    50
Name: label, dtype: int64
1    50
Name: label, dtype: int64
0    50
1    50
Name: label, dtype: int64
2    50
Name: label, dtype: int64


In [ ]:
from sklearn.model_selection import cross_val_score

df_clf = DecisionTreeClassifier()
scores = cross_val_score(dt_clf, X=iris_data, y=iris_label, scoring = 'accuracy', cv=3)
scores

array([0.98, 0.94, 1.  ])

In [ ]:
np.mean(scores)

0.9733333333333333

In [ ]:
dt_clf2 = DecisionTreeClassifier()
dt_clf2.fit(X_train, y_train)

dt_clf.fit(X_train, y_train)

pred1 = dt_clf.predict(X_test)
pred2 = dt_clf2.predict(X_test)

print(pred1)
print(pred2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
grid_param = {
    'max_depth': [1, 2, 3],
    'min_samples_split' : [2, 3, 4]
}
grid_param

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3, 4]}

In [ ]:
from sklearn.model_selection import GridSearchCV

dt_clf = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dt_clf, param_grid=grid_param, cv=3, refit=True)


In [ ]:
grid_dtree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [ ]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.681224                1   
1  {'max_depth': 1, 'min_samples_split': 3}         0.681224                1   
2  {'max_depth': 1, 'min_samples_split': 4}         0.681224                1   
3  {'max_depth': 2, 'min_samples_split': 2}         0.681224                1   
4  {'max_depth': 2, 'min_samples_split': 3}         0.681224                1   
5  {'max_depth': 2, 'min_samples_split': 4}         0.681224                1   
6  {'max_depth': 3, 'min_samples_split': 2}         0.681224                1   
7  {'max_depth': 3, 'min_samples_split': 3}         0.681224                1   
8  {'max_depth': 3, 'min_samples_split': 4}         0.681224                1   

   split0_test_score  split1_test_score  split2_test_score  
0           0.558824           0.969697           0.515152  
1           0.558824           0.969697           0.515152  
2           0.558824           0.969697           0.515152  
3           0.558824           0.969697           0.515152  
4           0.558824           0.969697           0.515152  
5           0.558824           0.969697           0.515152  
6           0.558824           0.969697           0.515152  
7           0.558824           0.969697           0.515152  
8           0.558824           0.969697           0.515152

In [ ]:
grid_dtree.best_params_

{'max_depth': 1, 'min_samples_split': 2}