In [43]:
from sklearn.datasets import load_iris

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [44]:
import pandas as pd

#읽어 들인 iris 정보를 데이터 프레임으로 변경
df_iris = pd.DataFrame(data=iris.data, columns = iris.feature_names)
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [45]:
df_iris.mean()
df_iris.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [46]:
from sklearn.preprocessing import StandardScaler

#표준화 클래스 로드
scaler = StandardScaler()
#표준화 클래스
scaler.fit(df_iris)
iris_scaled = scaler.transform(df_iris)
iris_scaled[:3]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [47]:
df_iris_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
df_iris_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [48]:
df_iris_scaled.mean()
df_iris_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [49]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(df_iris)
iris_Scaled = scaler.transform(df_iris)
iris_scaled[:3]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [50]:
import numpy as np

train_array = np.arange(0, 11).reshape(-1, 1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [51]:
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

#1. 파일 읽기

> 타이타닉 데이터를 읽어 들여 상위 3개의 데이터만 추출하시오

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [53]:
import pandas as pd

path = '/content/drive/MyDrive/2022_1_Study_AI/data/titanic.csv'
df_titanic = pd.read_csv(path)
df_titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

#2. 데이터 전처리

##2.1 결측치 처리

Age, Cabin, Embarked에 결측치가 발생된 것을 알 수 있다. Age는 나이로 평균을 이용하여 결측치를 해결하고 나머지 두 feature는 N이라는 값을 넣어 결측치를 해결하시오.

In [54]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [55]:
df_titanic['Age']
df_titanic['Age'].mean()
round(df_titanic['Age'].mean(), 0)

30.0

In [56]:
df_titanic['Age'].fillna(round(df_titanic['Age'].mean(), 0))
df_titanic['Age']
# df_titanic['Age'].fillna(round(df_titanic['Age'].mean(), 0), inplace=True)
df_titanic['Age'] = df_titanic['Age'].fillna(round(df_titanic['Age'].mean(), 0))
df_titanic['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    30.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [57]:
df_titanic['Cabin']
df_titanic['Cabin'].fillna('N')
df_titanic['Cabin'].fillna('N', inplace = True)
df_titanic['Cabin']


0         N
1       C85
2         N
3      C123
4         N
       ... 
886       N
887     B42
888       N
889    C148
890       N
Name: Cabin, Length: 891, dtype: object

In [58]:
df_titanic['Embarked']
df_titanic['Embarked'].fillna('N')
df_titanic['Embarked'].fillna('N', inplace=True)
df_titanic['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

##2.2 이상치 처리

In [59]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.758889    0.523008   
std     257.353842    0.486592    0.836071   13.002570    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   30.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [60]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [61]:
df_titanic['Sex'].value_counts()
df_titanic['Cabin'].value_counts()
df_titanic['Ticket'].value_counts()
df_titanic['Embarked'].value_counts()

S    644
C    168
Q     77
N      2
Name: Embarked, dtype: int64

##2.3 문자열 수치화

In [62]:
from sklearn import preprocessing

features=['Sex', 'Cabin', 'Embarked']

for feature in features:
  # LabelEncoder는 문자를 수치화하는 함수
  le = preprocessing.LabelEncoder()
  le.fit(df_titanic[feature])
  df_titanic[feature] = le.transform(df_titanic[feature])

df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  Cabin  Embarked  
0         A/5 21171   7.2500    146         3  
1          PC 17599  71.2833     81         0  
2  STON/O2. 3101282   7.9250    146         3  
3            113803  53.1000     55         3  
4            373450   8.0500    146         3

In [63]:
# df_titanic.drop(['Name', 'Ticket'], axis=1, inplace =True)
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  Cabin  Embarked  
0         A/5 21171   7.2500    146         3  
1          PC 17599  71.2833     81         0  
2  STON/O2. 3101282   7.9250    146         3  
3            113803  53.1000     55         3  
4            373450   8.0500    146         3

#3. 모델 만들기

##3.1 훈련 / 검증 데이터 만들기

> Quiz. 생존에 따른 데이터를 분석할 것이다. 다음 조건에 맞게 훈련용 데이터와 테스트용 데이터를 추출하시오.

*   Label 정보는 Survived를 이용한다.
*   나머지 정보를 Data로 활용한다.
*   테스트 데이터는 30%를 사용한다.
*   random_State는 62로 고정한다.

In [64]:
from sklearn.model_selection import train_test_split

# Label 정보는 Survived를 이용한다.
df_label = df_titanic['Survived']
# 나머지 정보를 Data로 활용한다.
df_data = df_titanic.drop(['Survived'], axis=1)
# 테스트 데이터는 30%를 사용한다.
# random_state는 62로 고정한다.
X_train, X_test, y_train, y_test = train_test_split(df_data, df_label, test_size=0.3, random_state=62)

##3.2 결정트리

In [65]:
from sklearn.tree import DecisionTreeClassifier

# 모델 로드
dt_clf = DecisionTreeClassifier()
# 학습
dt_clf.fit(X_train, y_train)
# 예측
pred = dt_clf.predict(X_test)
pred

ValueError: ignored

In [ ]:
from sklearn.metrics import accuracy_score

# 정확도
accuracy_score(y_test, pred)

##3.3 랜덤 포레스트

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# 모델 로드
rf_clf = RandomForestClassifier()
# 학습
rf_clf.fit(X_train, y_train)
# 예측
pred = rf_clf.predict(X_test)
pred

In [ ]:
from sklearn.metrics import accuracy_score

# 정확도
accuracy_score(y_test, pred)

##3.4 로지스틱 회귀

In [ ]:
from sklearn.linear_model import LogisticRegression
# 모델 로드
lr = LogisticRegression(max_iter=1000)
# 학습
lr.fit(X_train, y_train)
# 예측
pred = lr.predict(X_test)
pred

In [ ]:
from sklearn.metrics import accuracy_score
# 정확도
accuracy_score(y_test, pred)

#4. 교차 검증

##4.1 cross_val_score

###4.1.1 결정트리

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_clf, df_data, df_label, cv=5)
scores
np.mean(scores)

###4.1.2 랜덤 포레스트

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_clf, df_data, df_label, cv=5)
scores
np.mean(scores)

###4.1.3 로지스틱 회귀

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr, df_data, df_label, cv=5)
scores
np.mean(scores)


##4.2 GridSearchCV

###4.2.1 결정트리

In [ ]:
params = {
    'max_depth':[2, 3, 5, 10],
    'min_samples_split':[2,3,5],
    'min_samples_leaf':[1,5,8]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_dt_clf = GridSearchCV(dt_clf, param_grid=params, scoring='accuracy', cv=5)
grid_dt_clf.fit(X_train, y_train)

In [ ]:
# 최적에 파라미터 확인
grid_dt_clf.best_params_

In [ ]:
# 최적의 파라미터 적용된 최고 정확도 점수
grid_dt_clf.best_score_

In [ ]:
# 최적의 파라미터가 적용된 모델로 X_test의 정확도 확인
best_model = grid_dt_clf.best_estimator_
pred = best_model.predict(X_test)
accuracy_score(y_test, pred)

###4.2.2 랜덤 포레스트

In [ ]:
params = {
    'max_depth':[2, 3, 5, 10],
    'min_samples_split':[2,3,5],
    'min_samples_leaf':[1,5,8]
}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_rf_clf = GridSearchCV(rf_clf, param_grid=params, scoring='accuracy', cv=5)
grid_rf_clf.fit(X_train, y_train)

In [ ]:
# 최적에 파라미터 확인
grid_rf_clf.best_params_

In [ ]:
# 최적의 파라미터 적용된 최고 정확도 점수
grid_rf_clf.best_score_

In [ ]:
# 최적의 파라미터가 적용된 모델로 X_test의 정확도 확인
best_model = grid_rf_clf.best_estimator_
pred = best_model.predict(X_test)
accuracy_score(y_test, pred)

###4.2.3 로지스틱 회귀

In [ ]:
params = {
    'C' : [2, 3, 5, 10],
    'penalty' : ['12'],
    'max_iter' : [1000]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_lr = GridSearchCV(lr, param_grid=params, scoring='accuracy', cv=5)
grid_lr.fit(X_train, y_train)

In [ ]:
# 최적에 파라미터 확인
grid_lr.best_params_

In [ ]:
# 최적의 파라미터 적용된 최고 정확도 점수
grid_lr.best_score_

In [ ]:
# 최적의 파라미터가 적용된 모델로 X_test의 정확도 확인
best_model = grid_lr.best_estimator_
pred = best_model.predict(X_test)
accuracy_score(y_test, pred)